arb-dir: lib/l10n
template-arb-file: app_en.arb
output-dir: lib/l10n/gen
output-class: ModuleALocalizations
output-localization-file: module_a_localizations.dart
synthetic-package: false # set this as false to import the delegate in the main project  
nullable-getter: false
