name: applanga_flutter
description: With ApplangaFlutter you can easily manage your (over-the-air) translations with tiny changes to your codebase.
version: 3.0.59
homepage: https://github.com/applanga/applanga_flutter

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  petitparser: ^6.0.2
  yaml: ^3.1.1
  analyzer: ^7.0.0
  dart_style: ^3.0.1
  synchronized: ^3.0.0+3
  intl: ^0.20.2
  path: ^1.8.0
  ansicolor: ^2.0.2
  web: ^1.1.0
  pub_semver: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  build: ^2.4.1

flutter:
  plugin:
    platforms:
      android:
        package: com.applanga.applanga_flutter
        pluginClass: ApplangaFlutterPlugin
      ios:
        pluginClass: ApplangaFlutterPlugin
      macos:
        pluginClass: ApplangaFlutterPlugin
      windows:
        pluginClass: ApplangaFlutterPlugin
      linux:
        pluginClass: ApplangaFlutterPlugin
      web:
        pluginClass: ApplangaFlutterWeb
        fileName: applanga_flutter_web.dart