name: applanga_flutter
description: ApplangaSDK for Flutter.
version: 0.0.10
author: Applanga <info@applanga.com>
homepage: https://github.com/applanga/applanga_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.applanga.applangaflutter
    pluginClass: ApplangaFlutterPlugin

