name: applanga_flutter
description: ApplangaSDK for Flutter.
version: 0.0.12
homepage: https://github.com/applanga/applanga_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_driver:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
        android:
          package: com.applanga.applangaflutter
          pluginClass: ApplangaFlutterPlugin
        ios:
          pluginClass: ApplangaFlutterPlugin
