name: applanga_flutter
description: With ApplangaFlutter you can easily manage your (over-the-air) translations with tiny changes to your codebase.
version: 3.0.61
homepage: https://github.com/applanga/applanga_flutter

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  petitparser: ^7.0.1
  yaml: ^3.1.3
  analyzer: ^7.0.0
  dart_style: ^3.0.1
  synchronized: ^3.4.0
  intl: ^0.20.2
  path: ^1.9.1
  ansicolor: ^2.0.3
  web: ^1.1.1
  pub_semver: ^2.2.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  build: ^4.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.applanga.applanga_flutter
        pluginClass: ApplangaFlutterPlugin
      ios:
        pluginClass: ApplangaFlutterPlugin
      macos:
        pluginClass: ApplangaFlutterPlugin
      windows:
        pluginClass: ApplangaFlutterPlugin
      linux:
        pluginClass: ApplangaFlutterPlugin
      web:
        pluginClass: ApplangaFlutterWeb
        fileName: applanga_flutter_web.dart