name: applanga_flutter
description: With ApplangaFlutter you can easily manage your (over-the-air) translations with tiny changes to your codebase.
version: 3.0.46
homepage: https://github.com/applanga/applanga_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  petitparser: ^5.1.0
  yaml: ^3.1.1
  analyzer: ^5.2.0
  dart_style: ^2.2.4
  synchronized: ^3.0.0+3
  intl: ^0.17.0
  path: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  build: ^2.3.1

flutter:
  plugin:
    platforms:
      android:
        package: com.applanga.applanga_flutter
        pluginClass: ApplangaFlutterPlugin
      ios:
        pluginClass: ApplangaFlutterPlugin
      macos:
        pluginClass: ApplangaFlutterPlugin
      windows:
        pluginClass: ApplangaFlutterPlugin
      linux:
        pluginClass: ApplangaFlutterPlugin
      web:
        pluginClass: ApplangaFlutterWeb
        fileName: applanga_flutter_web.dart