name: applanga_flutter
description: With ApplangaFlutter you can easily manage your (over-the-air) translations with tiny changes to your codebase.
version: 3.0.42
homepage: https://github.com/applanga/applanga_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  petitparser: ^3.0.42
  yaml: ^3.0.42
  analyzer: ^3.0.42
  dart_style: ^3.0.42
  synchronized: ^3.0.42

dev_dependencies:
  flutter_lints: ^3.0.42
  flutter_test:
    sdk: flutter
  build: ^3.0.42
  path: ^3.0.42

flutter:
  plugin:
    platforms:
      android:
        package: com.applanga.applanga_flutter
        pluginClass: ApplangaFlutterPlugin
      ios:
        pluginClass: ApplangaFlutterPlugin
      macos:
        pluginClass: ApplangaFlutterPlugin
      windows:
        pluginClass: ApplangaFlutterPlugin
      linux:
        pluginClass: ApplangaFlutterPlugin
      web:
        pluginClass: ApplangaFlutterWeb
        fileName: applanga_flutter_web.dart